Project/shop/IdmanistFinal/Idmanist.Admin/Controllers/ProductController.cs
using IdmanistCore.Infrastructure;
using IdmanistData.Model;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebGrease.Css.Extensions;

namespace Idmanist.Admin.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductRepository _productRepository;
        private readonly ICategoryRepository _categoryRepository;
        private readonly IProductImageRepository _productImageRepository;
        public ProductController(IProductRepository productRepository,ICategoryRepository categoryRepository, IProductImageRepository productImageRepository/*, IBrandRepository brandRepository*/)
        {
            _productRepository = productRepository;
            _categoryRepository = categoryRepository;
            _productImageRepository = productImageRepository;
            //_BrandRepository = brandRepository
        }
        // GET: Product
        public ActionResult Index()
        {
            var productList = _productRepository.GetAll().ToList();
            return View(productList);
        }

        public ActionResult Create()
        {
            SetCategoryList();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Product product, HttpPostedFileBase productImage)
        {
            if (!ModelState.IsValid)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (productImage!=null && productImage.ContentLength>0)
            {
                var img = new ProductImage()
                {
                    ImageName = Path.GetFileName(productImage.FileName),
                    ContentType = productImage.ContentType
                };
                using (var reader = new BinaryReader(productImage.InputStream))
                {
                    img.Content = reader.ReadBytes(productImage.ContentLength);
                }
                product.ProductImages = new List<ProductImage> { img };
            }
            _productRepository.Insert(product);
            _productRepository.Save();
            return RedirectToAction("Index");
            
        }

        
        
        public ActionResult Edit(int ? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var product = _productRepository.GetById(id.Value);
            if (product == null)
            {
                return HttpNotFound();
            }

            SetCategoryList(product.CategoryId);
            return View(product);

        }

        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult Edit(Product product, HttpPostedFileBase productImage)
        {
            if (!ModelState.IsValid)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            _productRepository.Update(product);
            _productRepository.Save();

            if (productImage == null || productImage.ContentLength <= 0)
            {
                return RedirectToAction("Index");
            }

            var img = new ProductImage()
            {
                ImageName = Path.GetFileName(productImage.FileName),
                ContentType = productImage.ContentType
            };

            using (var reader = new BinaryReader(productImage.InputStream))
            {
                img.Content = reader.ReadBytes(productImage.ContentLength);
                img.ProductId = product.ProductId;
            }

            var existingImage = _productRepository.GetById(product.ProductId).ProductImages;
            if (existingImage!=null && existingImage.Count > 0)
            {
                existingImage.ForEach(x => _productImageRepository.Delete(x.ImageId));

            }


            _productImageRepository.Insert(img);
            _productImageRepository.Save();

            return RedirectToAction("Index");

        }

        public ActionResult Details(int ? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var product = _productRepository.GetById(id.Value);
            if (product == null)
            {
                return HttpNotFound();
            }
           
            return View(product);
        }

        public ActionResult Delete(int ? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var product = _productRepository.GetById(id.Value);
            if (product == null)
            {
                return HttpNotFound();
            }

            return View(product);
        }

        [HttpPost, ValidateAntiForgeryToken, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            _productRepository.Delete(id);
            _productRepository.Save();
            return RedirectToAction("Index");
        }


        public void SetCategoryList(object category = null)
        {
            var categoryList = _categoryRepository.GetAll().ToList();
            var selectList = new SelectList(categoryList, "CategoryId", "CategoryName", category);
            ViewData.Add("CategoryId", selectList);
        }
    }
}

Project/shop/IdmanistFinal/Idmanist.Admin/Controllers/ProductFeatureController.cs
using IdmanistCore.Infrastructure;
using IdmanistData.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Idmanist.Admin.Controllers
{
    public class ProductFeatureController : Controller
    {
        private IProductRepository _productRepository;
        private IProductFeatureRepository _productFeatureRepository;
        public ProductFeatureController( IProductRepository productRepository, IProductFeatureRepository productFeatureRepository)
        {
            _productRepository = productRepository;
            _productFeatureRepository = productFeatureRepository;
        }
        // GET: ProductFeature
        public ActionResult Index(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var product = GetCurrentProduct(id.Value);
            var productFeatures = product.ProductFeatures;
            ViewBag.SelectedProduct = product;


            return View(productFeatures);

        }

        public ActionResult Create(int ? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var product = _productRepository.GetById(id.Value);
            ViewBag.SelectedProduct = product;

            return View();

        }
        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult Create(int? id, ProductFeature productFeature)
        {
            productFeature.ProductId = id.Value;
            _productFeatureRepository.Insert(productFeature);
            _productFeatureRepository.Save();
            return RedirectToAction("Index", new { id = id.Value });
        }
        private Product GetCurrentProduct(int id)
        {
            var product = _productRepository.GetById(id);
            return product;
        }

        public ActionResult Details(int? id, int? productId)
        {
            if (id == null || productId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var product = GetCurrentProduct(id.Value);
            ViewBag.SelectedProduct = product;
            var productFeature = _productFeatureRepository.GetById(id.Value);
            if (productFeature == null)
            {
                return HttpNotFound();
            }
            return View(productFeature);
        }

        public ActionResult Edit(int? id, int? productId)
        {
            if (id == null || productId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var product = _productRepository.GetById(productId.Value);
            ViewBag.SelectedProduct = product;
            var productFeature = _productFeatureRepository.GetById(id.Value);
            if (productFeature == null)
            {
                return HttpNotFound();
            }
            return View(productFeature);
        }


        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult Edit(ProductFeature productFeature)
        {
            if (!ModelState.IsValid)
            {
                return View(productFeature);
            }
            _productFeatureRepository.Update(productFeature);
            _productFeatureRepository.Save();
            return RedirectToAction("Index", new { id = productFeature.ProductId });
        }


        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var productFeature = _productFeatureRepository.GetById(id.Value);
            if (productFeature == null)
            {
                return HttpNotFound();
            }

            return View(productFeature);
        }

        [HttpPost, ValidateAntiForgeryToken, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            _productFeatureRepository.Delete(id);
            _productFeatureRepository.Save();
            return RedirectToAction("Index");
        }
    }
}

Project/shop/IdmanistFinal/Idmanist.Admin/Views/Product/Create.cshtml
@model IdmanistData.Model.Product
@{
    ViewBag.Title = "Yeni məhsul ";
}

<h2>Yeni məhsul</h2>

@using (Html.BeginForm("Create", "Product", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
@Html.AntiForgeryToken()
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "" , new {@class ="text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Category, htmlAttributes: new {@class="control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryId", null, htmlAttributes: new { @class="form-control"})
                
                @Html.ValidationMessageFor(model => model.Category,"", new { @class = "text-danger"})

            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductName, htmlAttributes:new { @class="control-label  col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model =>model.ProductName , new { htmlAttributes= new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductName, "", new { @class = "text-danger" })
            
            </div>

        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Product_date, htmlAttributes: new { @class = "control-label  col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Product_date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Product_date, "", new { @class = "text-danger" })

            </div>

        </div>

        <div class="form-group"> 
            @Html.Label("Şəkil", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="productImage"  />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input  type="submit" value="Yadda saxla" class="btn btn-default"/>

            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink("Siyahıya qayıt", "Index")

</div>

@section scripts
{
@Scripts.Render("~/bundles/jqueryval")    
}

Project/shop/IdmanistFinal/Idmanist.Admin/Views/Product/Delete.cshtml
@model IdmanistData.Model.Product

@{
    ViewBag.Title = "Sil";
}

<h2>Sil</h2>

<h3>Bu məhsulu silmək istədiyinizdən əminsiniz?</h3>
<div>
    <h4>Product</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProductName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CategoryId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CategoryId)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Sil" class="btn btn-default" /> |
            @Html.ActionLink("Siyahıya qayıt", "Index")
        </div>
    }
</div>

Project/shop/IdmanistFinal/Idmanist.Admin/Views/Product/Details.cshtml
@model IdmanistData.Model.Product
@{
    ViewBag.Title = "Məhsul detalları";
}

<h2>Məhsul detalları</h2>
<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Category.CategoryName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Category.CategoryName)
        </dd>
    </dl>

    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProductName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ProductName)
        </dd>
    </dl>
    @{
        var productFirstImage = Model.ProductImages.FirstOrDefault();
        if (productFirstImage != null)
        {
           <dl class="dl-horizontal">
               <dt>

               </dt>
               <dd>
                   <div class="form-group">
                       <div class="col-md-10">
                           <img src="@string.Format("data: {0}; base64, {1} ", productFirstImage.ContentType, Convert.ToBase64String(productFirstImage.Content))" alt="Alternate Text" />
                           @*@Html.Base64Image(productFirstImage)*@
                           </div>
                       </div>

               </dd>
           </dl>
        }

    }

    <p>
        @Html.ActionLink("Dəyişdir","Edit", new { id= Model.ProductId}) |
        @Html.ActionLink("Siyahıya qayıt", "Index")
    </p>
</div>

Project/shop/IdmanistFinal/Idmanist.Admin/Views/Product/Edit.cshtml
@model IdmanistData.Model.Product
@{
    ViewBag.Title = "Məhsul dəyişdir ";
}

<h2>Yeni məhsul</h2>

@using (Html.BeginForm("Create", "Product", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
@Html.AntiForgeryToken()
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "" , new {@class ="text-danger" })
        @Html.HiddenFor(model => model.ProductId )
        <div class="form-group">
            @Html.LabelFor(model => model.Category, htmlAttributes: new {@class="control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryId", null, htmlAttributes: new { @class="form-control"})
                @Html.ValidationMessageFor(model => model.Category,"", new { @class = "text-danger"})

            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductName, htmlAttributes:new { @class="control-label  col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model =>model.ProductName , new { htmlAttributes= new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductName, "", new { @class = "text-danger" })
            
            </div>

        </div>

        @{
            var productFirstImage = Model.ProductImages.FirstOrDefault();
            if (productFirstImage != null)
            {
                <div class="form-group">
                    <div class="col-md-10">
                        <img src="@string.Format("data: {0}; base64, {1} ", productFirstImage.ContentType, Convert.ToBase64String(productFirstImage.Content))" alt="Alternate Text" />
                        @*@Html.Base64Image(productFirstImage)*@
                    </div>
                </div>
            }

        }

        <div class="form-group"> 
            @Html.Label("Şəkil", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="productImage"  />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input  type="submit" value="Yadda saxla" class="btn btn-default"/>

            </div>
        </div>

    </div>
}
<div>
    @Html.ActionLink("Siyahıya qayıt", "Index")
    @Html.ActionLink("Xüsusiyyətlər", "Index","ProductFeature", new { id= Model.ProductId}, new { }) |
</div>

@section scripts
{
@Scripts.Render("~/bundles/jqueryval")    
}

Project/shop/IdmanistFinal/Idmanist.Admin/Views/Product/Index.cshtml
@model IEnumerable<IdmanistData.Model.Product>
@{
    ViewBag.Title = "Index";
}

<h2>Məhsullar</h2>
<p>
    @Html.ActionLink("Yeni məhsul", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model=>model.Category.CategoryName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProductName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Product_date)
        </th>
        <th>

        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(model => item.Category.CategoryName)
            </td>
            <td>
                @Html.DisplayFor(model => item.ProductName)
            </td>
            <td>
                @Html.DisplayFor(model => item.Product_date)
            </td>
            <td>
                @Html.ActionLink("Dəyişdir","Edit", new { id= item.ProductId}) |
                @Html.ActionLink("Detallar","Details", new { id = item.ProductId}) |
                @Html.ActionLink("Sil", "Delete", new { id= item.ProductId})



            </td>
        </tr>
    }
</table>