Project/shop/IdmanistFinal/Idmanist.Web/Controllers/AllProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Idmanist.Web.Controllers
{
    public class AllProductsController : Controller
    {
        // GET: AllProducts
        public ActionResult Index()
        {
            return View();
        }
    }
}

Project/shop/IdmanistFinal/Idmanist.Web/Controllers/ProductController.cs
using Idmanist.Web.ViewModels;
using IdmanistCore.Infrastructure;
using IdmanistData.DataContext;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Idmanist.Web.Controllers
{
    public class ProductController : Controller
    {
        private readonly ICategoryRepository _categoryRepository;
        private readonly IProductRepository _productRepository;
        public ProductController(ICategoryRepository categoryRepository, IProductRepository productRepository)
        {
            _categoryRepository = categoryRepository;
            _productRepository = productRepository;
        }
        // GET: Product
        public ActionResult Index(int? id)
        {
            IdmanistDataContext db = new IdmanistDataContext();
            ProdInViewModel model = new ProdInViewModel();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            
            var product = _productRepository.GetById(id.Value);
          
            if (product == null)
            {
                return HttpNotFound();
            }
            model.Categories = db.Category.ToList();
            model.RelatedProducts = _productRepository.GetAll().Where(o => o.ProductId != id && o.CategoryId == product.CategoryId).Take(8).ToList();
            model.Product = product;
            model.wishesss = db.Wishes.ToList();
            model.NextProduct = _productRepository.GetAll().FirstOrDefault(n => n.ProductId > product.ProductId && n.CategoryId == product.CategoryId);
            model.PrevProduct = _productRepository.GetAll().OrderByDescending(x => x.ProductId).FirstOrDefault(p => p.ProductId < product.ProductId && p.CategoryId == product.CategoryId);
            return View(model);
        }

        public ActionResult AllProducts(int? id, int? page)
        {
            IdmanistDataContext db = new IdmanistDataContext();
            ProdInViewModel model = new ProdInViewModel();
            if (id == null || page == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            model.Categories = db.Category.ToList();
            model.Category = db.Category.Find(id);
            int pageNumber = (page ?? 1);
            model.Products = db.Product.OrderBy(o => o.Product_Price).Where(c => c.CategoryId == id).ToPagedList(pageNumber, 5);
            return View(model);
        }
    }
}

Project/shop/IdmanistFinal/Idmanist.Web/Controllers/SearchController.cs
using IdmanistData.DataContext;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PagedList;

namespace Idmanist.Web.Controllers
{
    public class SearchController : Controller
    {
        // GET: Search
        // GET: Search
        IdmanistDataContext db = new IdmanistDataContext();
        [HttpGet]
        public ActionResult Index(int? id, string searchString)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            int pageNumber = id ?? 1;
            ViewBag.searchStr = searchString;

            if (!String.IsNullOrEmpty(searchString))
            {
                int count = db.Product.Where(b => b.ProductName.Contains(searchString)).Count();
                ViewBag.ResultCount = count;
                if (count != 0)
                {
                    ViewBag.Searching = db.Product.Where(b => b.ProductName.Contains(searchString)).OrderBy(o => o.ProductId).ToPagedList(pageNumber, 12);

                }
                else
                {
                    ViewBag.NoResult = "Belə bir nəticə tapılmadı";
                    id = 1;
                }

            }
            else
            {
                ViewBag.EmptyString = "Axtarış daxil edilmədi";
                id = 1;
            }
            return View();
        }

        [HttpPost]
        public JsonResult LiveSearch(string searchString)
        {
            var blogTitles = db.Product.Where(b => b.ProductName.Contains(searchString)).Select(b => new { ProductID = b.ProductId, ProductNAME = b.ProductName.Substring(0, 20) }).ToList();
            return Json(blogTitles, JsonRequestBehavior.AllowGet);
        }
    }
}

Project/shop/IdmanistFinal/Idmanist.Web/Controllers/WishedController.cs
using IdmanistData.DataContext;
using IdmanistData.Model;
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;

namespace Idmanist.Web.Controllers
{
    public class WishedController : Controller
    {
        // GET: Wished
        public ActionResult Index()
        {
            using (IdmanistDataContext db = new IdmanistDataContext())
            {
                if (Session["user"] != null)
                {
                    Customer  thisUser = (Customer)(Session["user"]);
                
                    var  mywishes = db.Wishes.Include(w => w.Product).Where(x => x.customer_id == thisUser.UserID).ToList();
                    return View(mywishes);

                }
                else
                {
                    return RedirectToAction("login", "user");
                }
            }
        
        }
    }
}

Project/shop/IdmanistFinal/Idmanist.Web/Views/Shared/MainMenu.cshtml
@*@model IEnumerable<IdmanistData.Model.Category>
    <nav>
    <div class="container">
        <div class="nav-inner">
            @if (Model.Any())
            {

                
                <ul id="nav" class="hidden-xs">
                    @foreach (var category in Model)
                {
                        <li id="nav-home" class="level0 parent drop-menu">
                            @Html.ActionLink(category.CategoryName, "AllProducts", "Product", new { id = category.CategoryId, Page })
                        </li>
                    }
                </ul>

            }
        </div>
    </div>
</nav>*@

Project/shop/IdmanistFinal/Idmanist.Web/Views/Shared/_FeaturedProducts.cshtml
@model Idmanist.Web.ViewModels.ProdInViewModel


<section class="featured-pro container wow bounceInUp animated">
    <div class="slider-items-products">
        <div class="new_title center">
            <h2>Featured Products</h2>
        </div>
        <div id="featured-slider" class="product-flexslider hidden-buttons">
            <div class="slider-items slider-width-col4">

                @foreach (var product in Model.FeaturedProducts)
                {
                      <!-- Item -->
                    <div class="item">
                        <div class="col-item">
                            <div class="sale-label sale-top-right">Sale</div>
                            <div class="product-image-area">
                                <a class="product-image" title="Sample Product" href="@Url.Action("Index","Product", new { id= product.ProductId})"> <img src="~/Content/products-images/product1.jpg" class="img-responsive" alt="product-image" /> </a>
                                <a title="Add to Wishlist" class="link-wishlist" href="wishlist.html"><span></span></a>
                                <div class="actions-links"><span class="add-to-links"> <a title="magik-btn-quickview" class="magik-btn-quickview" href="quick_view.html"><span>quickview</span></a> 

                                                               @{
                                                                   IdmanistData.Model.Customer thisuser = (IdmanistData.Model.Customer)(Session["user"]);

                                                                   if (Session["user"] == null)
                                                                   {
                                                                    <a class="link-wishlist" data-id="@product.ProductId" href="#">
                                                                        <i class="fa fa-heart-o fa-lg"></i><span>@product.mywishes  </span>
                                                                    </a>

                                                                   }
                                                                   else if (new List<dynamic>(Model.wishesss).FirstOrDefault(a => a.customer_id == thisuser.UserID && a.product_id == product.ProductId) != null || Ajax.ViewBag.wished == true)
                                                                   {
                                                                       <a class="link-wishlist unlike" data-id="@product.ProductId" href="javascript:void(0)">
                                                                           <i class="fa fa-heart fa-lg text-danger"></i><span>@product.mywishes  </span>
                                                                       </a>
                                                                   }
                                                                   else
                                                                   {
                                                                       <a class="link-wishlist like" data-id="@product.ProductId" href="javascript:void(0)">
                                                                           <i class="fa fa-heart-o fa-lg"></i><span>@product.mywishes  </span>
                                                                       </a>
                                                                   }
                                                               }
                                    <a title="Add to Compare" class="link-compare" href="compare.html"><span>Add to Compare</span></a></span>
                                
                                </div>






                            </div>
                            <div class="info">
                                <div class="info-inner">
                                    <div class="item-title"> <a title=" Sample Product" href= "#">@Html.ActionLink(product.ProductName, "Index", "Product", new { id = product.ProductId }, new { })  </a> </div>
                                    <!--item-title-->
                                    <div class="item-content">
                                        <div class="ratings">
                                            <div class="rating-box">
                                                <div class="rating"></div>
                                            </div>
                                        </div>
                                        <div class="price-box">
                                            <p class="special-price"> <span class="price"> @product.Product_Price </span> </p>
                                            @*<p class="old-price"> <span class="price-sep">-</span> <span class="price"> $50.00 </span> </p>*@
                                        </div>
                                    </div>
                                    <!--item-content-->
                                </div>
                                <!--info-inner-->
                                <div class="actions">
                                    <button type="button" title="Add to Cart" class="button btn-cart"><span>Add to Cart</span></button>
                                </div>
                                <!--actions-->

                                <div class="clearfix"> </div>
                            </div>
                        </div>
                    </div>
                <!-- End Item -->
                }
              
             
            </div>
        </div>
    </div>
</section>

Project/shop/IdmanistFinal/Idmanist.Web/Views/Shared/_UserProfile.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/Content/css/profilstyle.css">
    <link rel="stylesheet" href="~/Content/css/colors/main.css" id="colors">

    <link rel="stylesheet" href="~/Content/css/icons.css" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    @RenderSection("wishCss", false)
</head>
<body>

    <div id="wrapper">
        <!-- Header Container
        ================================================== -->
        <header id="header-container" class="fixed fullwidth dashboard">
            <!-- Header -->
            <div id="header" class="not-sticky" style="background: #65d31f;">
                <div class="container">
                    <!-- Left Side Content -->
                    <div class="left-side">
                        <!-- Mobile Navigation -->
                        <!-- Main Navigation / End -->
                    </div>
                    <!-- Left Side Content / End -->
                    <!-- Right Side Content / End -->
                    <div class="right-side">
                        <!-- Header Widget -->
                        <div class="header-widget">
                            <!-- User Menu -->
                            <div class="user-menu">
                                <div class="user-nme">
                                    <a href="@Url.Action("Index", "Home")" style="color:white;">Ana səhifə<i class="fa fa-home" aria-hidden="true" style="margin-left:5px; font-size: 20px;"></i></a>
                                    <a href="@Url.Action("index", "user")" style="color:white; margin-left:20px;">Hesabım<i class="fa fa-user-circle-o" aria-hidden="true" style="margin-left:5px; font-size: 20px;"></i></a>
                                </div>
                            </div>
                        </div>
                        <!-- Header Widget / End -->
                    </div>
                    <!-- Right Side Content / End -->
                </div>
            </div>
            <!-- Header / End -->
        </header>
        <div class="clearfix"></div>
        <!-- Header Container / End -->
        <!-- Dashboard -->
        <div id="dashboard" style="background-color:none!important;">
            <!-- Navigation
            ================================================== -->
            <!-- Responsive Navigation Trigger -->
            <a href="#" class="dashboard-responsive-nav-trigger"><i class="fa fa-reorder"></i> Dashboard Navigation</a>
            <div class="dashboard-nav">
                <div class="dashboard-nav-inner" style="height:450px;">
                    <ul data-submenu-title="Siyahılarım">
                        <li class="active">
                            <a href="@Url.Action("Index", "Wished")"> <i class="fa fa-book" aria-hidden="true"></i>Bəyəndiklərim</a>
                        </li>

                        @*<li><a href="@Url.Action("Index", "Meqale")"><i class="fa fa-pencil-square" aria-hidden="true"></i> Məqalə Göndər</a></li>*@
                    </ul>
                    <ul data-submenu-title="Account">
                        <li class="active"><a href="@Url.Action("Index", "user")"><i class="fa fa-address-book" aria-hidden="true"></i> Profilim</a></li>
                        <li><a href="@Url.Action("Logout", "user")"><i class="fa fa-sign-out" aria-hidden="true"></i> Çıxış</a></li>
                    </ul>
                </div>
            </div>
            <!-- Navigation / End -->
            <!-- Content
            ================================================== -->
            <!-- Content / End -->
            
            @RenderBody()

        </div>
        <!-- Dashboard / End -->

    </div>
    <!-- Dashboard / End -->
    <!--wrapper ends-->


    <script type="text/javascript" src="~/Content/js/jsscripts/jquery-2.2.0.min.js"></script>
    <script type="text/javascript" src="~/Content/js/jsscripts/jpanelmenu.min.js"></script>
    <script type="text/javascript" src="~/Content/js/jsscripts/chosen.min.js"></script>
    <script type="text/javascript" src="~/Content/js/jsscripts/slick.min.js"></script>
    <script type="text/javascript" src="~/Content/js/jsscripts/rangeslider.min.js"></script>
    <script type="text/javascript" src="~/Content/js/jsscripts/magnific-popup.min.js"></script>
    <script type="text/javascript" src="~/Content/js/waypoints.min.js"></script>
    <script type="text/javascript" src="~/Content/js/jsscripts/counterup.min.js"></script>
    <script type="text/javascript" src="~/Content/js/jquery-ui.min.js"></script>
    <script type="text/javascript" src="~/Content/js/jsscripts/tooltips.min.js"></script>
    <script type="text/javascript" src="~/Content/js/jsscripts/custom.js"></script>

    <script type="text/javascript" src="~/Content/js/dropzone.js"></script>



</body>
</html>

Project/shop/IdmanistFinal/Idmanist.Web/Views/Shared/_header.cshtml
@using IdmanistData.Model;

@{
    var u = Session["user"] as Customer;
}
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />    
<header class="header-container">
    <div class="header-top">
        <div class="container">
            <div class="row">
                <!-- Header Language -->
                <div class="col-xs-6">
                    <div class="dropdown block-language-wrapper">
                        <a role="button" data-toggle="dropdown" data-target="#" class="block-language dropdown-toggle" href="#"> <img src="images/english.png" alt="language"> English <span class="caret"></span> </a>
                        <ul class="dropdown-menu" role="menu">
                            <li role="presentation"><a role="menuitem" tabindex="-1" href="#"><img src="images/english.png" alt="language"> English </a></li>
                            <li role="presentation"><a role="menuitem" tabindex="-1" href="#"><img src="images/francais.png" alt="language"> French </a></li>
                            <li role="presentation"><a role="menuitem" tabindex="-1" href="#"><img src="images/german.png" alt="language"> German </a></li>
                        </ul>
                    </div>

                    <!-- End Header Language -->
                    <!-- Header Currency -->
                    <div class="dropdown block-currency-wrapper">
                        <a role="button" data-toggle="dropdown" data-target="#" class="block-currency dropdown-toggle" href="#"> USD <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li role="presentation"><a role="menuitem" tabindex="-1" href="#"> $ - Dollar </a></li>
                            <li role="presentation"><a role="menuitem" tabindex="-1" href="#"> £ - Pound </a></li>
                            <li role="presentation"><a role="menuitem" tabindex="-1" href="#"> € - Euro </a></li>
                        </ul>
                    </div>

                    <!-- End Header Currency -->

                    <div class="welcome-msg hidden-xs"> Default welcome msg! </div>
                </div>
                <div class="col-xs-6">

                    <!-- Header Top Links -->

                    @{

                        if (Session["user"] == null)
                        {

                            <div class="toplinks">
                                <div class="links">
                                    @*<div class="myaccount"><a title="My Account" href="login.html"><span class="hidden-xs">My Account</span></a></div>
                                        <div class="wishlist"><a title="My Wishlist" href="wishlist.html"><span class="hidden-xs">Wishlist</span></a></div>
                                        <div class="check"><a title="Checkout" href="checkout.html"><span class="hidden-xs">Checkout</span></a></div>
                                        <div class="login"><a title="Login" href="login.html"><span class="hidden-xs">Log In</span></a></div>*@
                                    <a href="@Url.Action("Register", "user")">Qeydiyyat <i class="fa fa-user login_icon" aria-hidden="true"></i></a>
                                    <a href="@Url.Action("Login", "user")">Giriş <i class="fa fa-sign-in login_icon" aria-hidden="true"></i></a>
                                </div>
                            </div>

                        }
                        else
                        {
                            <div class="login-details" style="float:right;margin-top:12px;">
                                <p class="login">
                                    <a href="@Url.Action("index", "user")" style="color:white; margin-left:20px;"><i class="fa fa-user-circle-o" aria-hidden="true" style="margin-left:5px; font-size: 20px;"></i> @u.UserName</a>
                                </p>
                            </div>
                        }

                    }







                    <!-- End Header Top Links -->
                </div>
            </div>
        </div>
    </div>
    <div class="header container">
        <div class="row">
            <div class="col-lg-2 col-sm-3 col-md-2">
                <!-- Header Logo -->
                <a class="logo" title="Magento Commerce" href="index.html"><img alt="Magento Commerce" src="images/logo.png"></a>
                <!-- End Header Logo -->
            </div>
            <div class="col-lg-8 col-sm-6 col-md-8">
                <!-- Search-col -->
                <div class="search-box">
                    <form action="@Url.Action("Index", "Search", new { id = 1 })" method="get" class="formSearch" autocomplete="off">
                
                        <input type="text" placeholder="Axtar . . . "  class="" name="searchString" id="searchString">
                        <button id="submit-button" class="search-btn-bg" type="submit" value="submit"><span>Axtar</span></button>
                        <ul id="searchingResult" class="searchingResult"></ul>
                    </form>
                </div>
                <!-- End Search-col -->
            </div>
            <!-- Top Cart -->
            <div class="col-lg-2 col-sm-3 col-md-2">
                <div class="top-cart-contain">
                    <div class="mini-cart">
                        <div data-toggle="dropdown" data-hover="dropdown" class="basket dropdown-toggle">
                            <a href="#">
                                <i class="glyphicon glyphicon-shopping-cart"></i>
                                <div class="cart-box"><span class="title">cart</span><span id="cart-total">2 item </span></div>
                            </a>
                        </div>
                        <div>
                            <div class="top-cart-content arrow_box">
                                <div class="block-subtitle">Recently added item(s)</div>
                                <ul id="cart-sidebar" class="mini-products-list">
                                    <li class="item even">
                                        <a class="product-image" href="#" title="Downloadable Product "><img alt="Downloadable Product " src="products-images/product3.jpg" width="80"></a>
                                        <div class="detail-item">
                                            <div class="product-details">
                                                <a href="#" title="Remove This Item" onClick="" class="glyphicon glyphicon-remove">&nbsp;</a> <a class="glyphicon glyphicon-pencil" title="Edit item" href="#">&nbsp;</a>
                                                <p class="product-name"> <a href="product_detail.html" title="Downloadable Product">Sample Product </a> </p>
                                            </div>
                                            <div class="product-details-bottom"> <span class="price">$100.00</span> <span class="title-desc">Qty:</span> <strong>1</strong> </div>
                                        </div>
                                    </li>
                                    <li class="item last odd">
                                        <a class="product-image" href="#" title="  Sample Product "><img alt="  Sample Product " src="products-images/product2.jpg" width="80"></a>
                                        <div class="detail-item">
                                            <div class="product-details">
                                                <a href="#" title="Remove This Item" onClick="" class="glyphicon glyphicon-remove">&nbsp;</a> <a class="glyphicon glyphicon-pencil" title="Edit item" href="#">&nbsp;</a>
                                                <p class="product-name"> <a href="#" title="  Sample Product "> Sample Product </a> </p>
                                            </div>
                                            <div class="product-details-bottom"> <span class="price">$320.00</span> <span class="title-desc">Qty:</span> <strong>2</strong> </div>
                                        </div>
                                    </li>
                                </ul>
                                <div class="top-subtotal">Subtotal: <span class="price">$420.00</span></div>
                                <div class="actions">
                                    <button class="btn-checkout" type="button"><span>Checkout</span></button>
                                    <button class="view-cart" type="button"><span>View Cart</span></button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div id="ajaxconfig_info">
                        <a href="#/"></a>
                        <input value="" type="hidden">
                        <input id="enable_module" value="1" type="hidden">
                        <input class="effect_to_cart" value="1" type="hidden">
                        <input class="title_shopping_cart" value="Go to shopping cart" type="hidden">
                    </div>
                </div>
            </div>
            <!-- End Top Cart -->
        </div>
    </div>
</header>

Project/shop/IdmanistFinal/Idmanist.Web/Views/Shared/_topNav.cshtml
@model Idmanist.Web.ViewModels.ProdInViewModel

<nav>
    <div class="container">
        <div class="nav-inner">
      @if (Model != null)
      {
        <ul id="nav" class="hidden-xs">
            @foreach (var category in Model.Categories)
                {
                <li id="nav-home" class="level0 parent drop-menu">
                    <a href="@Url.Action("AllProducts", "Product", new {id=category.CategoryId,page=1})">@category.CategoryName</a>
                </li>
            }
        </ul>
      }
               

            
        </div>
    </div>
</nav>